name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Add your Docker Hub username in GitHub secrets
        password: ${{ secrets.DOCKER_HUB_TOKEN }}      # Add your Docker Hub token in GitHub secrets

    - name: Build the Docker image
      id: build
      run: |
        TAG=$(date +%s)
        docker build . --file Dockerfile --tag test:$TAG
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Push the Docker image to Docker Hub
      run: docker push test:$TAG
