name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}      # Docker Hub username stored in secrets
          password: ${{ secrets.DOCKER_HUB_TOKEN }}         # Docker Hub token stored in secrets

      - name: Tag the Docker image
        run: |
          IMAGE_TAG=my-image-name:latest
          docker tag my-image-name:$(date +%s) $IMAGE_TAG

      - name: Push the Docker image to Docker Hub
        run: docker push my-image-name:latest
